name: Build and Release Spring Boot Project

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 22
        uses: actions/setup-java@v4
        with:
          java-version: '22'
          distribution: 'adopt'

      - name: Build with Maven
        run: mvn package -B

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            target/daemonjar-*.jar
